# Generated by Django 5.0 on 2026-05-09 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0003_department_remove_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='completed_date',
        ),
    ]
