# Generated by Django 5.0 on 2026-05-09 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0004_remove_enrollment_completed_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_id',
            new_name='student_number',
        ),
    ]
